Repository DummyRu/DummyRu, pull requests merged in 2022-10, with the labels that each got.

#3 Updated message
  New Template.html
Labels: hacktoberfest, hacktoberfest-accepted

#4 Updated the template
  New Template.html
Labels: hacktoberfest, hacktoberfest-accepted

#5 Added styling changes
  New Template.html
Labels: hacktoberfest, hacktoberfest-accepted

#6 2022 message added
  README.md
Labels: hacktoberfest

#7 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#8 Update New Template.html
  New Template.html
Labels: hacktoberfest-accepted

#11 Added server initiation code
  index.ts
Labels: hacktoberfest, hacktoberfest-accepted

#10 Modified template
  New Template.html
Labels: hacktoberfest, hacktoberfest-accepted

#13 Added initial route
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#14 updated styling and refactored code
  New Template.html
Labels: hacktoberfest, hacktoberfest-accepted

#15 cleaned code and modified styling
  New Template.html
Labels: hacktoberfest, hacktoberfest-accepted

#16 Added home page
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#17 Update README.md
  README.md
Labels: hacktoberfest-accepted

#18 Updated styling
  New Template.html
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added new route
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#20 Update index.js
  index.js
Labels: hacktoberfest-accepted

#21 Update index.js
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#23 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 added additional pages
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#26 updated final read me
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#25 updated read me
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 added error page
  index.js
Labels: hacktoberfest, hacktoberfest-accepted
